### ISSUE TITLE
Wrong useragent

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-agent#246]
Hi,  @Ivans51 

As you can see, the useragent from the MDM Agent apear as:
_Apache-HttpClient/UNAVAILABLE (java 1.4)_
Should be:
**Inventory Agent/0.0.0 (Linux; Android 7.0; Flyve MDM)**

![image](https://user-images.githubusercontent.com/663460/50259380-25ad3780-0404-11e9-966a-07fde9cd5042.png)

![image](https://user-images.githubusercontent.com/663460/50259400-38c00780-0404-11e9-956e-40ada77c227a.png)

![image](https://user-images.githubusercontent.com/663460/50259460-74f36800-0404-11e9-96b3-1b75e206f033.png)

Reference:
https://github.com/flyve-mdm/android-mdm-agent/issues/663

**Comment by stonebuzz** [comment]
UserAgent fix by #281
