### ISSUE TITLE
Custom installation script for mass smartphone

### ISSUE THREAD

**Issue by mrcssilvasouza** [glpi-project/android-inventory-agent#250]
Mr,

Is there a script for apk, to customize the application installation with glpi server information in the "/ server settings / add server / server address" path and the below functions enabled?

Boot options
Notifications
Health Report
Usage Data
Automatic inventory
Frequency = day

**Comment by stonebuzz** [comment]
Hi @mrcssilvasouza 

actually not,

but if you want contribute financially  
to add this feature you can contact us -> sales@teclib.com

Best regards
