### ISSUE TITLE
Send IMEI device

### ISSUE THREAD

**Issue by MarcosRaiCunha** [glpi-project/android-inventory-agent#318]
The agent can access the device's IMEI, but does not send it to the glpi. Would that be a mistake or is that so?

**Comment by stonebuzz** [comment]
Hi @MarcosRaiCunha 

actually FusionInventory plugin is not compatible with this data.

We are currently working on the native GLPi inventory, which should be released after version 9.5.

Best regards

**Comment by MarcosRaiCunha** [comment]
Hi @stonebuzz 

Thanks for information!
