### ISSUE TITLE
Cyrillic characters

### ISSUE THREAD

**Issue by SabNK** [glpi-project/android-inventory-agent#319]
Cyrillic symbols in GLPI are question marked "?"

**Screenshots**
[https://i.imgur.com/Pq8e5ko.png](url)

**Smartphone (please complete the following information):**
 - Xiaomi Redmi Note 7
 - OS: Pie Android
![Pq8e5ko](https://user-images.githubusercontent.com/5380894/77200048-e257e200-6afa-11ea-9b4a-f07489c0f3a2.png)

**Comment by SabNK** [comment]
Maybe here you should setContentEncoding to UTF-8
https://github.com/glpi-project/android-inventory-agent/blob/develop/app/src/main/java/org/glpi/inventory/agent/utils/DataLoader.java
![2020-03-20 22_46_45-android-inventory-agent_DataLoader java at develop · glpi-project_android-invent](https://user-images.githubusercontent.com/5380894/77201024-ce14e480-6afc-11ea-98bf-01338a08e3f9.png)

**Comment by SabNK** [comment]
I just leave it here
https://stackoverflow.com/questions/25125781/encode-decode-httppost-utf-8-java/34824452

**Comment by stonebuzz** [comment]
Hi @SabNK thanks for feedback,

can you attach to this isue, xml inventroy from this device ?

Best regards

**Comment by SabNK** [comment]
Hi, the file has a lot of confidential info, like macaddress, I prefer not to share this info. 
This is a screen of the xml, if not enough give me an idea what do you need.
![android glpi cyrillic](https://user-images.githubusercontent.com/5380894/77292271-041aba00-6cf1-11ea-98b0-68af0d712b9f.png)

**Comment by kofe88** [comment]
I have same problem.
The inventory agent I use is: GLPI Android Agent (version 2020/01/07)
FusionInventory 9.5.0+1.0 on GLPI 9.5.1. The server is Ubuntu 18.04.1
The dataterminal: Urovo i6200s, Android 5.5

**Comment by stonebuzz** [comment]
Hi, can you test develop branch ?

Best regards

**Comment by stonebuzz** [comment]
Hi 
The problem come from the library in charge of making the inventory and creating the XML

can you open issue here -> https://github.com/flyve-mdm/android-inventory-library

Best regards

**Comment by stonebuzz** [comment]
Hi all,
can you test this PR ?

Best regards

**Comment by stonebuzz** [comment]
Fixed by #324
