### ISSUE TITLE
The GLPI Inventory Agent takes information of a SIM card, but it is not present in GLPI

### ISSUE THREAD

**Issue by kofe88** [glpi-project/android-inventory-agent#322]
Inventory Agent/1.0.0 (Linux; Android 5.1.1; GLPI Inventory Agent
GLPI Android Agent (version 2020/01/07)
GLPI 9.5.1
FusionInventory 9.5.0+1.0
In inventory.xml this data:

`<SIMCARDS> <COUNTRY><![CDATA[ru]]></COUNTRY> <OPERATOR_CODE><![CDATA[2502]]></OPERATOR_CODE> <OPERATOR_NAME><![CDATA[MegaFon]]></OPERATOR_NAME> <SERIAL><![CDATA[897010210860111111FF]]></SERIAL> <STATE><![CDATA[SIM_STATE_READY]]></STATE> <LINE_NUMBER><![CDATA[+79311111111]]></LINE_NUMBER> <SUBSCRIBER_ID><![CDATA[1]]></SUBSCRIBER_ID> </SIMCARDS>`

But it is not imported to GLPI.

**Comment by trasher** [comment]
Hello,

Since information is present in the XML file, the agent seems to do its job. fusioninventory plugin does not handle simcards for now (as far as I remember), maybe take a look at flyvemdm plugin.

**Comment by kofe88** [comment]
> Hello,
> 
> Since information is present in the XML file, the agent seems to do its job. fusioninventory plugin does not handle simcards for now (as far as I remember), maybe take a look at flyvemdm plugin.

Hello! Thank you for the answer, but unfortunately flyvemdm plugin apparently does not support GLPI > 9.5 yet :(

![4321](https://user-images.githubusercontent.com/16879167/92481807-88a1bc00-f1ef-11ea-96d5-1b7cb212c601.JPG)
