### ISSUE TITLE
Support OCS

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/android-inventory-agent#98]
Hi, @btry 

We need to test the Inventory Agent with OCS

- [ ] Deploy OCS
- [ ] Add  URL
- [ ] Run inventory

**Comment by ajsb85** [comment]
Hi, @DIOHz0r  

You can help us with this task.
In your local instance of GLPI try to deploy the OCS and test the Inventory Agent

Thank you.

**Comment by DIOHz0r** [comment]
Sure,

FYI I think that I read about OSC inventory support has been deprecated by fusioninventory somewhere. If I found that info I will let you know

**Comment by ajsb85** [comment]
I know it for the version 3.0 of FI.
Help us with the report about it.
To see if we can add this compatibility from our agents.
